language: python
sudo: false
python:
- 2.7.11

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install pip-accel
  - pip-accel install ansible
  - pip-accel install -r requirements/development.txt

before_script:
- export DATABASE_URL=postgres://postgres@localhost/sutta_contri
- psql -c "CREATE DATABASE sutta_contri;" -U postgres

script:
- flake8
- py.test --cov -v --tb=native
- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]

deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: sutta_contri-dev
    qa: sutta_contri-qa
    prod: sutta_contri-prod
  on:
    repo: aniketmaithani/sutta-contri-web
