# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuttaRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand_of_cig', models.CharField(help_text='Brand of the Cigg', max_length=100)),
                ('number_of_cig', models.CharField(help_text='Number of Cig you want to order', max_length=100)),
                ('money_given', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Sutta Requirement',
                'verbose_name_plural': 'Sutta Requirements',
            },
        ),
    ]
